services:
  {{PROJECT_NAME}}-dev-env:
    image: 'mmaarouf/{{PROJECT_NAME}}-dev-env:latest'
    container_name: '{{PROJECT_NAME}}-dev-env'
    build:
        context: .
    stdin_open: true
    tty: true
    volumes:
        - ${PROJECT_DIR}:${PROJECT_DIR}
    working_dir: ${PROJECT_DIR}